name: Deploy Website

on:
  push:
    branches:
      - sveltekit  # 本番ブランチ

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # リポジトリをチェックアウト

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Node.jsのバージョンを指定
      env:
          VITE_MICROCMS_API_KEY: ${{ secrets.VITE_MICROCMS_API_KEY }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # ビルドコマンド


    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}  # サーバーのホスト名
        username: ${{ secrets.ACCOUNT }}  # SSHユーザー名
        password: ${{ secrets.SSH_PASSWORD }}  # SSHパスワード
        port: ${{ secrets.SSH_PORT }}  # SSHポート
        source: "build/*"  # ビルドされたファイルがあるディレクトリ
        target: "/home/users/2/main.jp-yuuki-okubo/web/yuuki-okubo"  # サーバー上のディレクトリ
